/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{ts,tsx}',
    './src/vendor/**/*.{ts,tsx,js}',
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#fd5201',
          subtle: '#fff8f5',
          'extra-light': '#ffede5',
          light: '#fe9767',
          hover: '#fe7434',
          focused: '#fe7434',
          selected: '#cb4101',
          'surface-disabled': '#ffb999',
          border: '#fd5201',
          'border-light': '#ffb999',
          'border-darker': '#983101',
          text: '#fd5201',
          'text-light': '#fe9767',
          'text-dark': '#983101',
          'text-disabled': '#fff8f5',
        },
        neutral: {
          DEFAULT: '#000000',
          dark: '#949494',
          negative: '#ffffff',
          'extra-subtle': '#fafafa',
          subtle: '#f2f2f2',
          light: '#e0e0e0',
          hover: '#404040',
          focused: '#404040',
          selected: '#000000',
          'surface-disabled': '#d4d4d4',
          border: '#000000',
          'border-light': '#ededed',
          'border-strong': '#e0e0e0',
          'border-xstrong': '#d4d4d4',
          text: '#000000',
          'text-light': '#8a8a8a',
          'text-dark': '#404040',
          'text-disabled-dark': '#949494',
          'text-disabled-light': '#d4d4d4',
          'text-negative': '#ffffff',
          'text-medium': '#c4c4c4',
        },
        'accent-yellow': {
          DEFAULT: '#ffdb57',
          subtle: '#fff9e5',
          light: '#fff3c7',
          hover: '#ffe78f',
          focused: '#fff3c7',
          selected: '#ffd129',
          'surface-disabled': '#ffe78f',
          border: '#ffdb57',
          'border-light': '#fff3c7',
          'border-darker': '#ffd129',
          text: '#f5c000',
          'text-light': '#ffdb57',
          'text-dark': '#947400',
        },
        'accent-blue': {
          DEFAULT: '#99b4ff',
          subtle: '#f5f8ff',
          light: '#ebf0ff',
          hover: '#d3dfff',
          focused: '#d3dfff',
          selected: '#618bff',
          'surface-disabled': '#d3dfff',
          border: '#99b4ff',
          'border-light': '#ebf0ff',
          'border-darker': '#618bff',
          text: '#99b4ff',
          'text-dark': '#245eff',
        },
        'accent-purple': {
          DEFAULT: '#b38cf3',
          subtle: '#f3edfd',
          light: '#e7dafb',
          hover: '#ceb5f7',
          focused: '#ceb5f7',
          selected: '#9b67ef',
          'surface-disabled': '#ceb5f7',
          border: '#b38cf3',
          'border-light': '#e7dafb',
          'border-darker': '#9b67ef',
          text: '#b38cf3',
          'text-dark': '#8242eb',
        },
        success: {
          DEFAULT: '#5bb95e',
          subtle: '#f1f9f1',
          light: '#c2e5c3',
          hover: '#7ec881',
          focused: '#7ec881',
          selected: '#429a45',
          'surface-disabled': '#c2e5c3',
          border: '#5bb95e',
          'border-light': '#e2f3e3',
          'border-darker': '#317233',
          text: '#5bb95e',
          'text-dark': '#317233',
        },
        error: {
          DEFAULT: '#f23c3c',
          subtle: '#feecec',
          light: '#f78c8c',
          hover: '#f46161',
          focused: '#f46161',
          selected: '#e10f0f',
          'surface-disabled': '#fab3b3',
          border: '#e10f0f',
          'border-light': '#fab3b3',
          'border-darker': '#ac0b0b',
          text: '#e10f0f',
          'text-light': '#f78c8c',
          'text-dark': '#ac0b0b',
          'text-disabled': '#fcd9d9',
        },
      },
      spacing: {
        xxxs: '4px',
        xxs: '8px',
        xs: '12px',
        s: '16px',
        m: '20px',
        l: '24px',
        xl: '32px',
        xxl: '40px',
        xxxl: '48px',
        xxxxl: '56px',
        '5xl': '72px',
      },
      borderRadius: {
        none: '0px',
        xxxs: '4px',
        xxs: '8px',
        xs: '12px',
        sn: '16px',
        m: '20px',
        ln: '24px',
        xl: '32px',
        xxl: '40px',
        xxxl: '48px',
        full: '999px',
      },
      boxShadow: {
        card: '0px 2px 8px rgba(0, 0, 0, 0.08)',
        sm: '0px 1px 4px rgba(0, 0, 0, 0.06)',
        md: '0px 2px 8px rgba(0, 0, 0, 0.08)',
        lg: '0px 4px 16px rgba(0, 0, 0, 0.10)',
        xl: '0px 8px 32px rgba(0, 0, 0, 0.12)',
        '2xl': '0px 16px 48px rgba(0, 0, 0, 0.16)',
      },
      fontFamily: {
        default: ['"Founders Grotesk"', 'sans-serif'],
        display: ['"Tiempos Headline"', 'serif'],
      },
    },
  },
  plugins: [],
}
